### ISSUE TITLE
wire nlp/annotate to scigraph service

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/biolink-api#223] opened 2018-09-10 22:30 UTC
nlp/annotate doesn't seem to connect properly to backend [example](https://api.monarchinitiative.org/api/nlp/annotate/Searching%20for%20prospective%20vanadium-based%20agents%20against%20Trypanosoma%20cruzi%2C%20the%20parasite%20causing%20Chagas%20disease%2C%20four%20new%20%5BVVO(8HQ-H)(L-2H)%5D%20compounds%2C%20where%208HQ%20is%208-hydroxyquinoline%20and%20L%20are%20tridentate%20salicylaldehyde%20semicarbazone%20derivatives%20L1-L4%2C%20were%20synthesized%20and%20characterized%20in%20the%20solid%20state%20and%20in%20solution.%20The%20compounds%20were%20evaluated%20on%20T.%20cruzi%20epimastigotes%20(CL%20Brener)%20as%20well%20as%20on%20VERO%20cells%2C%20as%20mammalian%20cell%20model.%20Compounds%20showed%20activity%20against%20T.%20cruzi%20(IC50%206.2-10.5%20%CE%BCM)%20of%20the%20same%20order%20than%20Nifurtimox%20and%208HQ%2C%20and%20a%20four-%20to%20sevenfold%20activity%20increase%20with%20respect%20to%20the%20free%20semicarbazones.%20For%20comparison%2C%20%5BVVO2(L-H)%5D%20series%20was%20prepared%20and%20the%20new%20%5BVVO2(L3-H)%5D%20was%20fully%20characterized.%20They%20showed%20negligible%20activity%20and%20low%20selectivity%20towards%20the%20parasite.%20The%20inclusion%20of%208HQ%20as%20ligand%20in%20%5BVVO(8HQ-H)(L-2H)%5D%20compounds%20led%20to%20good%20activities%20and%20increased%20selectivity%20towards%20the%20parasite%20with%20respect%20to%208HQ.%2051V%20NMR%20experiments%2C%20performed%20to%20get%20insight%20into%20the%20nature%20of%20the%20active%20species%2C%20suggested%20partial%20decomposition%20of%20the%20compounds%20in%20solution%20to%20%5BVVO2(L-H)%5D%20and%208HQ.%20Depending%20on%20the%20dose%2C%20the%20compounds%20act%20as%20trypanocide%20or%20trypanostatic.%20A%20high%20uptake%20of%20vanadium%20in%20the%20parasites%20(58.51-88.9%25%20depending%20on%20dose)%20and%20a%20preferential%20accumulation%20in%20the%20soluble%20protein%20fraction%20of%20the%20parasite%20was%20determined.%20Treated%20parasites%20do%20not%20seem%20to%20show%20a%20late%20apoptotic%2Fnecrotic%20phenotype%20suggesting%20a%20different%20cell%20death%20mechanism.%20In%20vivo%20toxicity%20study%20on%20zebrafish%20model%20showed%20no%20toxicity%20up%20to%20a%2025%20%C2%B5M%20concentration%20of%20%5BVVO(8HQ-H)(L1-2H)%5D.%20These%20compounds%20could%20be%20considered%20prospective%20anti-T.%20cruzi%20agents%20that%20deserve%20further%20research.):

gives 404: 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by nathandunn** [comment] 2018-09-10 22:30
Should probably be a POST instead of a GET.

**Comment by monicacecilia** [comment] 2019-08-06 18:40
I am assuming that we no longer need to worry about this issue, given https://github.com/monarch-initiative/monarch-ui/pull/138
@kshefchek - requesting to close this ticket, please.

**Comment by kshefchek** [comment] 2019-08-06 19:01
I still think we want this via biolink instead of directly from scigraph, and if not we need to remove the rest function that is currently 404ing.

**Comment by monicacecilia** [comment] 2019-08-06 20:22
Agreed. Doing this via BioLink would be a good next step. 

I cannot reproduce the error on the production site nor on the beta site. So I may be misunderstanding where I'm supposed to be looking. 

- What is https://api.monarchinitiative.org/api/nlp/annotate/ ? - This is where I'm getting a 404. 
- I don't understand what @nathandunn means by 'backend example' above in the description. Nathan, is this available somewhere else on our website? (Apologies, I know this ticket is about to turn 1 year old, so memory might be rusty). 
- Where did this error originate in the first place?
  - I took the same [abstract](https://www.ncbi.nlm.nih.gov/pubmed/30194536) that is embedded in the search string in the URL from the description of this ticket, and used it in the new Text Annotator on the beta site; I am able to get results in https://beta.monarchinitiative.org/tools/text-annotate
  - I also used the same abstract in the Text Annotator currently on the production site and also was able to retrieve results ([see results here](https://monarchinitiative.org/annotate/text?q=Searching+for+prospective+vanadium-based+agents+against+Trypanosoma+cruzi%2C+the+parasite+causing+Chagas+disease%2C+four+new+%5BVVO%288HQ-H%29%28L-2H%29%5D+compounds%2C+where+8HQ+is+8-hydroxyquinoline+and+L+are+tridentate+salicylaldehyde+semicarbazone+derivatives+L1-L4%2C+were+synthesized+and+characterized+in+the+solid+state+and+in+solution.+The+compounds+were+evaluated+on+T.+cruzi+epimastigotes+%28CL+Brener%29+as+well+as+on+VERO+cells%2C+as+mammalian+cell+model.+Compounds+showed+activity+against+T.+cruzi+%28IC50+6.2-10.5+%CE%BCM%29+of+the+same+order+than+Nifurtimox+and+8HQ%2C+and+a+four-+to+sevenfold+activity+increase+with+respect+to+the+free+semicarbazones.+For+comparison%2C+%5BVVO2%28L-H%29%5D+series+was+prepared+and+the+new+%5BVVO2%28L3-H%29%5D+was+fully+characterized.+They+showed+negligible+activity+and+low+selectivity+towards+the+parasite.+The+inclusion+of+8HQ+as+ligand+in+%5BVVO%288HQ-H%29%28L-2H%29%5D+compounds+led+to+good+activities+and+increased+selectivity+towards+the+parasite+with+respect+to+8HQ.+51V+NMR+experiments%2C+performed+to+get+insight+into+the+nature+of+the+active+species%2C+suggested+partial+decomposition+of+the+compounds+in+solution+to+%5BVVO2%28L-H%29%5D+and+8HQ.+Depending+on+the+dose%2C+the+compounds+act+as+trypanocide+or+trypanostatic.+A+high+uptake+of+vanadium+in+the+parasites+%2858.51-88.9%25+depending+on+dose%29+and+a+preferential+accumulation+in+the+soluble+protein+fraction+of+the+parasite+was+determined.+Treated+parasites+do+not+seem+to+show+a+late+apoptotic%2Fnecrotic+phenotype+suggesting+a+different+cell+death+mechanism.+In+vivo+toxicity+study+on+zebrafish+model+showed+no+toxicity+up+to+a+25+%C2%B5M+concentration+of+%5BVVO%288HQ-H%29%28L1-2H%29%5D.+These+compounds+could+be+considered+prospective+anti-T.+cruzi+agents+that+deserve+further+research.&longestOnly=true)).

**Comment by kshefchek** [comment] 2019-08-06 20:35
Theres a api/nlp/{text} route that is not functional, for example
https://api-dev.monarchinitiative.org/api/nlp/annotate/test%20text

Both monarch legacy and beta use the scigraph annotator directly

**Comment by monicacecilia** [comment] 2019-08-07 00:59
Looks like this will be an issue for @deepakunni3. 👀

**Comment by deepakunni3** [comment] 2019-08-29 14:53
Yes, this should be easy to implement. I just have to route SciGraph annotator calls via BioLink API.

**Comment by deepakunni3** [comment] 2019-10-10 19:14
This is done via #317

**Closed as completed by deepakunni3** 2019-10-10 19:14 UTC
